from fixtures import *
app=QGuiApplication([]);f=Fixture('pilot')
print('cold',len(f.pages()),f.errors(),flush=True)
f.start_warm()
print('warm',len(f.pages()),len(named(f.root,'baseItem')),f.errors(),{k:v.fixtureWrites for k,v in f.keep.items() if v.fixtureWrites},flush=True)
f.open_menu(0);p=f.open_page('cameraSettingsImage')
print('selected',p.property('residentPresented'),p.testRows(),f.errors(),flush=True)
f.root.closeMenu();QTest.qWait(150)
print('closed',len(f.pages()),len(named(f.root,'baseItem')),f.errors(),flush=True)
f.close()
