"""生成固定 ICC 的精确快速表；区间不能确定的颜色仍走原整数公式。"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re

HERE = Path(__file__).resolve().parents[1]
SOURCE = HERE / "native/display_tables.h"
EXPECTED = "294321dd847b176bc3c359074eb2a014ef089a11e83a36cb85e13ac9b61d3e45"


def run():
    raw = SOURCE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == EXPECTED, "固定 1.25.0 色彩表已改变"
    text = raw.decode()

    def array(name):
        match = re.search(r"\b" + name + r"\[\d+\]\s*=\s*\{([^}]+)\}", text)
        assert match
        return [int(v) for v in re.findall(r"-?\d+", match.group(1))]

    linear, matrix, srgb = (array(n) for n in ("adobe_linear", "adobe_to_srgb", "srgb_encoded"))

    def encoded(n):
        n = (n + 524288) >> 20
        if n <= 0:
            return 0
        if n >= 1048576:
            return 255
        slot, part = n >> 8, n & 255
        return (srgb[slot] * (256 - part) + srgb[slot + 1] * part + 32896) // 65792

    def interval(lo, hi):
        a, b = encoded(lo), encoded(hi)
        # encoded 单调；两端相同即可覆盖第三分量的全部 256 个输入。
        return a if a == b else 256

    top = linear[-1]
    red = [interval(matrix[0] * r + matrix[1] * g,
                    matrix[0] * r + matrix[1] * g + matrix[2] * top)
           for r in linear for g in linear]
    green = [interval(matrix[3] * top + matrix[4] * g,
                      matrix[4] * g + matrix[5] * top) for g in linear]
    blue = [interval(matrix[6] * top + matrix[7] * g + matrix[8] * b,
                     matrix[7] * g + matrix[8] * b) for g in linear for b in linear]
    assert matrix[0] > 0 and matrix[1] < 0 and matrix[2] > 0
    assert matrix[3] < 0 and matrix[4] > 0 and matrix[5] > 0
    assert matrix[6] < 0 and matrix[7] < 0 and matrix[8] > 0
    lines = ["/* Generated by tools/generate_display_fast_tables.py.",
             " * 固定 1.25.0 ICC；值 256 表示仍需按原整数公式计算。 */"]
    for name, values in (("red", red), ("green", green), ("blue", blue)):
        lines.append(f"static const uint16_t fast_{name}[{len(values)}] = {{")
        lines += ["    " + ",".join(map(str, values[i:i + 32])) + "," for i in range(0, len(values), 32)]
        lines.append("};")
    target = HERE / "native/display_fast_tables.h"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    evidence = {
        "kind": "exact-monotone-interval-tables-not-camera-measurement",
        "inputSha256": EXPECTED,
        "outputSha256": hashlib.sha256(target.read_bytes()).hexdigest(),
        "tableBytes": 2 * (len(red) + len(green) + len(blue)),
        "ambiguousEntries": {"red": red.count(256), "green": green.count(256), "blue": blue.count(256)},
        "ambiguousBehavior": "Original fixed-point matrix and gamma expression; no approximation",
    }
    out = HERE / "artifacts/pixels"
    out.mkdir(parents=True, exist_ok=True)
    (out / "table-generation.json").write_text(json.dumps(evidence, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(evidence, ensure_ascii=False))


if __name__ == "__main__":
    run()
