require('./runtime-env.cjs')();
const { _electron: electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

(async () => {
  const root = path.resolve(__dirname, '..');
  const packaged = process.argv.includes('--packaged');
  const packageRoot = path.join(root, 'release', `Hasselblad-Debug-${require('../package.json').version}`);
  const evidence = path.join(root, 'research', 'validation', ...(packaged ? ['packaged'] : []));
  await fs.mkdir(evidence, { recursive: true });
  const env = { ...process.env };
  delete env.ELECTRON_RUN_AS_NODE;
  const client = await electron.launch({ executablePath: packaged ? path.join(packageRoot,'Hasselblad-Debug.exe') : require('electron'), args: packaged ? ['--smoke'] : [root, '--smoke'], cwd: packaged ? packageRoot : root, env, timeout: 20000 });
  const checks = [];
  try {
    const loadedRoot = await client.evaluate(({ app }) => app.getAppPath());
    assert.equal(path.resolve(loadedRoot), packaged ? path.join(packageRoot,'resources','app') : root);
    const page = await client.firstWindow();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.locator('.metric').first().waitFor();
    const config = await client.evaluate(({ BrowserWindow }) => {
      const window = BrowserWindow.getAllWindows()[0];
      const prefs = window.webContents.getLastWebPreferences();
      return { sandbox: prefs.sandbox, contextIsolation: prefs.contextIsolation, nodeIntegration: prefs.nodeIntegration, webSecurity: prefs.webSecurity };
    });
    assert.deepEqual(config, { sandbox: true, contextIsolation: true, nodeIntegration: false, webSecurity: true });
    const initial = await page.evaluate(async () => ({ node: typeof require, process: typeof process, state: await debugClient.snapshot() }));
    assert.equal(initial.node, 'undefined'); assert.equal(initial.process, 'undefined');
    assert.equal(initial.state.data.source, 'offline-static');
    assert.equal(initial.state.data.events.length, 0);
    checks.push('离线启动、Node 隔离、sandbox、受限 IPC');
    await page.screenshot({ path: path.join(evidence, 'overview-offline.png') });
    await page.locator('#simulate').click();
    await page.waitForFunction(() => document.querySelector('#source-title').textContent.includes('模拟诊断') && !document.querySelector('#simulate').disabled);
    assert.equal((await page.evaluate(() => debugClient.snapshot())).data.rows.length, 18);
    assert.ok(!(await page.locator('body').innerText()).includes('SYNTHETIC_'));
    await page.screenshot({ path: path.join(evidence, 'overview-simulated.png') });
    checks.push('模拟 HTTP → 主进程脱敏 → 界面来源标记');
    await page.locator('.nav-item[data-page="parameters"]').click();
    await page.locator('#category').selectOption('trigger');
    assert.equal(await page.locator('#parameter-results tbody tr').count(), 3);
    await page.locator('#parameter-search').fill('87');
    assert.equal(await page.locator('#parameter-results tbody tr').count(), 1);
    assert.ok((await page.locator('#parameter-results').innerText()).includes('客户端始终禁止写入'));
    checks.push('参数搜索、分类过滤、can_set 不启用写入');
    await page.locator('.nav-item[data-page="trigger"]').click();
    assert.equal(await page.locator('.trigger-node').count(), 5);
    await page.screenshot({ path: path.join(evidence, 'trigger-evidence.png') });
    await page.getByRole('heading', { name: '与引闪相关的参数快照' }).scrollIntoViewIfNeeded();
    assert.ok((await page.locator('#page-content').innerText()).includes('不表示实时充电就绪'));
    assert.ok((await page.locator('#page-content').innerText()).includes('不是相机事件日志'));
    await page.screenshot({ path: path.join(evidence, 'trigger-data.png') });
    await page.locator('.nav-item[data-page="region"]').click();
    assert.ok((await page.locator('#page-content').innerText()).includes('用户回忆'));
    await page.locator('#connect').click();
    assert.equal(await page.locator('#check-connect').innerText(), '读取六项调试快照');
    await page.locator('#check-connect').click();
    await page.locator('#toast').waitFor();
    assert.ok((await page.locator('#toast').innerText()).includes('未启用实机读取'));
    await page.locator('#disconnect').click();
    const session = (await page.evaluate(() => debugClient.snapshot())).data;
    assert.equal(session.hardwareRequests,0);
    assert.equal(session.events[0].outcome,'NO_SESSION');
    checks.push('三类触发链路和地区证据视图、测试实例实机读取隔离及空会话断开');
    await page.locator('.nav-item[data-page="firmware"]').click();
    assert.equal(await page.locator('#fw-read').isDisabled(), true);
    assert.ok((await page.locator('#page-content').innerText()).includes('尚未验证'));
    await page.locator('#toast').waitFor({ state: 'hidden', timeout: 12000 });
    await page.screenshot({ path: path.join(evidence, 'firmware-unconnected.png') });
    await page.locator('#fw-replay').click();
    await page.waitForFunction(() => document.querySelectorAll('#firmware-events tbody tr').length === 10);
    assert.ok((await page.locator('#page-content').innerText()).includes('人工格式回放'));
    const firmware = (await page.evaluate(() => debugClient.snapshot())).data.firmware;
    assert.equal(firmware.source, 'offline-replay'); assert.equal(firmware.lastRead, null);
    assert.equal((await page.evaluate(() => debugClient.readFirmware())).code, 'HARDWARE_DISABLED');
    await page.locator('#firmware-events tbody tr').nth(5).scrollIntoViewIfNeeded();
    assert.ok((await page.locator('#firmware-events').innerText()).includes('250000'));
    await page.screenshot({ path: path.join(evidence, 'firmware-replay.png') });
    checks.push('固件发射点详情/人工来源、未验证实机标记、测试实例 ADB 隔离');
    const bad = await page.evaluate(() => debugClient.simulate('http://192.0.2.1/'));
    assert.equal(bad.code,'IPC_DENIED');
    checks.push('渲染层无法通过 simulate 提交任意 URL');
    await page.locator('.nav-item[data-page="overview"]').click();
    await page.locator('#scenario').selectOption('unauthorized');
    await page.locator('#simulate').click();
    await page.waitForFunction(() => !document.querySelector('#simulate').disabled);
    assert.equal((await page.evaluate(() => debugClient.snapshot())).data.rows.length,0);
    assert.ok((await page.locator('#page-content').innerText()).includes('401'));
    checks.push('401 清除旧快照并显示停止原因');
    const fixture = path.join(root,'CodeTests','Fixtures','parameters.synthetic.json');
    await fs.mkdir(path.dirname(fixture),{recursive:true});
    // 测试固定人工数据，不使用设备采集。
    await fs.writeFile(fixture,JSON.stringify({'27':{can_get:true,can_set:false,value:'4.2.0',range:''},'22':{can_get:true,can_set:false,value:'PRIVATE_TEST_VALUE',range:''}}));
    await client.evaluate(({ dialog }, fixturePath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixturePath] }); },fixture);
    await page.locator('#import').click();
    await page.waitForFunction(() => document.querySelector('#source-title').textContent.includes('离线导入'));
    const imported = await page.evaluate(() => debugClient.snapshot());
    assert.equal(imported.data.rows.length,1); assert.equal(imported.data.hiddenFieldCount,1);
    const exported = await page.evaluate(() => debugClient.exportReport());
    const report = await fs.readFile(exported.data.path,'utf8');
    assert.ok(!report.includes('PRIVATE_TEST_VALUE')); assert.ok(report.includes('offline-import'));
    checks.push('原生导入流程、主进程过滤和脱敏报告落盘');
    await page.locator('#reset').click();
    await page.waitForFunction(() => document.querySelector('#source-title').textContent.includes('离线研究'));
    assert.equal((await page.evaluate(() => debugClient.snapshot())).data.events.length,0);
    const layout = await page.evaluate(() => ({width:innerWidth, scrollWidth:document.documentElement.scrollWidth}));
    assert.ok(layout.scrollWidth <= layout.width);
    assert.deepEqual(errors,[]);
    checks.push('清空恢复离线、无水平溢出、无 renderer 异常');
    await fs.writeFile(path.join(evidence,'ui-checks.json'),JSON.stringify({source:'local-electron-synthetic-tests',packaged,testedAt:new Date().toISOString(),hardwareRequests:0,checks,passed:true},null,2)+'\n');
    console.log(JSON.stringify({packaged,passed:checks.length,hardwareRequests:0,checks},null,2));
  } finally { await client.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
